{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dennis-healthcheckshost.serviceAccountName" . }}
  labels:
{{ include "dennis-healthcheckshost.labels" . | nindent 4 }}
{{- end -}}
